name: Test
on:
  - push
  - workflow_dispatch
jobs:
  test:
    runs-on: macos-12
    steps:
      - run: brew install tmux
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: dafyddj/action-sshd-cloudflared@master
      - if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
