name: Test
on:
  - workflow_dispatch
jobs:
  test-linux:
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
#      - uses: valeriangalliat/action-sshd-cloudflared@v1
#      - if: ${{ failure() }}
       - uses: mxschmitt/action-tmate@v3
  test-mac:
    runs-on: macos-12
    timeout-minutes: 1
    steps:
      - run: brew install tmux
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: dafyddj/action-sshd-cloudflared@master
      - if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
